[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TerraVide"
authors = [{name = "Sarang Pramode", email = "sp872@cornell.edu"}]
dynamic = ["version", "description"]
